### ISSUE TITLE
Preprocessing Error - IndexError: tuple index out of range

### ISSUE THREAD

**Issue by JonasMir** [calico/solo#44] opened 2020-07-13 15:11 UTC
Dear solo team,

First of all, thanks for your great tool! I have the following little problem: If I run solo (version 0.6) on CellRanger output, everything works fine. If I run it on one of the other optional formats, e.g. .loom or .h5ad, then I always get the same error quickly after start: "IndexError: tuple index out of range", involving the scvi/dataset package (version 0.6.5). It seems to have a problem with the gene names... My input files were created using scanpy (version 1.4.6), for example like adata.write('data.h5ad', force_dense=True). 

Since the solo results on the unfiltered CellRanger output for most of my samples is actually not correct (it tremendously underestimates the number of doublets, maybe due to cell cycle playing a large role in my samples?), I would really like to try it on filtered cells. Do you have any ideas regarding the aforementioned problem?

Thanks for your help!

Best,

Jonas

**Comment by njbernstein** [comment] 2020-07-13 16:09
Hi @JonasMir I can definitely help!

If you should share the full stack trace that would be very helpful.

Also, it would be helpful if you could send the `h5ad` file you are using to my email. nicholas at calicolabs.com

With these two things, I should definitely be able to help you. If you can't send the full data set only sending a fraction of it that creates the same error works as well.

**Comment by njbernstein** [comment] 2020-07-14 05:13
@JonasMir  following up here. if you can pass along that info it would be very helpful

**Comment by JonasMir** [comment] 2020-07-14 16:02
Hi Nicholas,

I did as you said. Please let me know, if you either have any problems accessing the data or need something else. 
Thanks for your support!

**Comment by njbernstein** [comment] 2020-07-14 17:34
Okay I believe the issue is that you have a column in your `obs` object named `_X`. If you rename that things play nice. This seems to be a bug on the scVI side of things. I'll file an issue with them. 

Let me know if that doesn't fix your problem but it did for me.

**Comment by njbernstein** [comment] 2020-07-14 17:45
issue is here: https://github.com/YosefLab/scVI/issues/704

I'm gonna close this, but please open this back up if this doesnt fix your issue

**Closed** 2020-07-14 17:47 UTC

**Comment by JonasMir** [comment] 2020-07-15 10:31
Perfect, that solved it for me. Thanks!
